require:
 - rubocop-md
 - rubocop-performance
 - rubocop-rake
 - rubocop-rspec

AllCops:
  Exclude:
    - exe/**/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - jekyll_outline.gemspec
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 20

Naming/FileName:
  Exclude:
    - Rakefile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/FilePath:
  IgnoreMethods: true
  SpecSuffixOnly: true
