require 'jekyll_plugin_support'
require 'rspec/match_ignoring_whitespace'
require_relative 'spec_helper'
require_relative '../lib/structure/outline'

RSpec.describe(JekyllSupport) do
  outline_options = JekyllSupport::OutlineOptions.new(pattern: '<b> title </b> &ndash; <i> description </i>')
  section1 = described_class::Section.new(outline_options, [0, 'Section 1'])
  section2 = described_class::Section.new(outline_options, [3, 'Section 2'])

  apages = [
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-01-01',
      description:     'This is the entry1 description.',
      draft:           true,
      last_modified:   '2023-01-01',
      order:           1,
      title:           'Entry 1',
      url:             'https://example.com/entry1'
    ),
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-01-02',
      description:     'This is the entry2 description.',
      last_modified:   '2023-01-02',
      order:           2,
      title:           'Entry 2',
      url:             'https://example.com/entry2'
    ),
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-10-03',
      description:     'This is the entry3 description.',
      last_modified:   '2024-10-03',
      order:           3,
      title:           'Entry 3',
      url:             'https://example.com/entry3'
    ),
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-10-04',
      description:     'This is the entry4 description.',
      draft:           true,
      last_modified:   '2024-10-04',
      order:           4,
      title:           'Entry 4',
      url:             'https://example.com/entry4'
    ),
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-10-05',
      description:     'This is the entry5 description.',
      last_modified:   '2024-10-05',
      order:           5,
      title:           'Entry 5',
      url:             'https://example.com/entry5'
    ),
    described_class.apage_from(
      collection_name: '_posts',
      date:            '2023-10-06',
      description:     'This is the entry6 description.',
      last_modified:   '2024-10-06',
      order:           6,
      title:           'Entry 6',
      url:             'https://example.com/entry6'
    )
  ]

  outline = described_class::Outline.new
  outline.add_sections [section1, section2]
  outline.add_entries apages

  _attribution = <<~END_ATT
    <div id="jps_attribute_570007" class="jps_attribute">
      <div>
        <a href="https://www.mslinn.com/jekyll_plugins/jekyll_outline.html" target="_blank" rel="nofollow">
          Generated by the jekyll_outline v1.2.1 Jekyll plugin, written by Mike Slinn 2024-01-09.
        </a>
      </div>
    </div>
  END_ATT

  expected_section1 = <<~END_EXPECTED
    <h3 class='post_title clear' id="title_0">Section 1</h3>
    <div id='posts_wrapper_0' class='clearfix'>
      <div id="posts_0" class='posts'>
        <span>2023-01-01</span>
        <span><a href='https://example.com/entry1'><b> Entry 1 </b> &ndash; <i> This is the entry1 description. </i> </a> <i class='jekyll_draft'>Draft</i></span>

        <span>2023-01-02</span>
        <span><a href='https://example.com/entry2'><b> Entry 2 </b> &ndash; <i> This is the entry2 description. </i> </a></span>
      </div>
    </div>
  END_EXPECTED

  expected_section2 = <<~END_EXPECTED
    <h3 class='post_title clear' id="title_3">Section 2</h3>
    <div id='posts_wrapper_3' class='clearfix'>
      <div id="posts_3" class='posts'>
        <span>2024-10-03</span>
        <span><a href='https://example.com/entry3'><b> Entry 3 </b> &ndash; <i> This is the entry3 description. </i> </a></span>

        <span>2024-10-04</span>
        <span><a href='https://example.com/entry4'><b> Entry 4 </b> &ndash; <i> This is the entry4 description. </i> </a> <i class='jekyll_draft'>Draft</i></span>

        <span>2024-10-05</span>
        <span><a href='https://example.com/entry5'><b> Entry 5 </b> &ndash; <i> This is the entry5 description. </i> </a></span>

        <span>2024-10-06</span>
        <span><a href='https://example.com/entry6'><b> Entry 6 </b> &ndash; <i> This is the entry6 description. </i> </a></span>
      </div>
    </div>
  END_EXPECTED

  it 'verifies initial values' do
    expect(outline.options.sort_by).to eq(:order)
  end

  it 'sorts by :order' do
    expect(outline.sort(apages)).to eq(apages)
  end

  it 'checks html shape' do
    expect(outline.sections.count).to eq(2)
    expect(outline.sections[0].children.count).to eq(2)
    expect(outline.sections[1].children.count).to eq(4)
  end

  it 'verifies html for first section' do
    actual = outline.sections[0].to_s
    expect(expected_section1).to match_ignoring_whitespace(actual)
  end

  it 'verifies html for second section' do
    actual = outline.sections[1].to_s
    expect(expected_section2).to match_ignoring_whitespace(actual)
  end

  it 'verifies generated html' do
    actual = outline.to_s

    expected = <<~END_EXPECTED
      <div class='outer_posts'>
        #{expected_section1}
        #{expected_section2}
      </div>
    END_EXPECTED

    expect(expected).to match_ignoring_whitespace(actual)
  end
end
