require 'jekyll_plugin_support'
require 'rspec/match_ignoring_whitespace'
require_relative 'spec_helper'
require_relative '../lib/structure/outline'

RSpec.describe(JekyllSupport) do
  section1 = described_class::Section.new([0, 'Section 1'])
  section2 = described_class::Section.new([3, 'Section 2'])

  apages = [
    described_class.apage_from(
      date:  '2023-10-01',
      draft: true,
      order: 1,
      title: 'Entry 1',
      url:   'https://example.com/entry1'
    ),
    described_class.apage_from(
      date:  '2023-10-02',
      order: 2,
      title: 'Entry 2',
      url:   'https://example.com/entry2'
    ),
    described_class.apage_from(
      date:  '2023-10-03',
      order: 3,
      title: 'Entry 3',
      url:   'https://example.com/entry3'
    ),
    described_class.apage_from(
      date:  '2023-10-04',
      draft: true,
      order: 4,
      title: 'Entry 4',
      url:   'https://example.com/entry4'
    ),
    described_class.apage_from(
      date:  '2023-10-05',
      order: 5,
      title: 'Entry 5',
      url:   'https://example.com/entry5'
    ),
    described_class.apage_from(
      date:  '2023-10-06',
      order: 6,
      title: 'Entry 6',
      url:   'https://example.com/entry6'
    )
  ]

  outline = described_class::Outline.new
  outline.add_sections [section1, section2]
  outline.add_entries apages

  _attribution = <<~END_ATT
    <div id="jps_attribute_570007" class="jps_attribute">
      <div>
        <a href="https://www.mslinn.com/jekyll_plugins/jekyll_outline.html" target="_blank" rel="nofollow">
          Generated by the jekyll_outline v1.2.1 Jekyll plugin, written by Mike Slinn 2024-01-09.
        </a>
      </div>
    </div>
  END_ATT

  expected_section1 = <<~END_EXPECTED
    <h3 class='post_title clear' id="title_0">Section 1</h3>
    <div id='posts_wrapper_0' class='clearfix'>
      <div id="posts_0" class='posts'>
        <span>2023-10-01</span>
        <span><a href='https://example.com/entry1'>Entry 1</a> <i class='jekyll_draft'>Draft</i></span>

        <span>2023-10-02</span>
        <span><a href='https://example.com/entry2'>Entry 2</a></span>
      </div>
    </div>
  END_EXPECTED

  expected_section2 = <<~END_EXPECTED
    <h3 class='post_title clear' id="title_3">Section 2</h3>
    <div id='posts_wrapper_3' class='clearfix'>
      <div id="posts_3" class='posts'>
        <span>2023-10-03</span>
        <span><a href='https://example.com/entry3'>Entry 3</a></span>

        <span>2023-10-04</span>
        <span><a href='https://example.com/entry4'>Entry 4</a> <i class='jekyll_draft'>Draft</i></span>

        <span>2023-10-05</span>
        <span><a href='https://example.com/entry5'>Entry 5</a></span>

        <span>2023-10-06</span>
        <span><a href='https://example.com/entry6'>Entry 6</a></span>
      </div>
    </div>
  END_EXPECTED

  it 'checks html shape' do
    expect(outline.sections.count).to eq(2)
    expect(outline.sections[0].children.count).to eq(2)
    expect(outline.sections[1].children.count).to eq(4)
  end

  it 'verifies html for first section' do
    actual = outline.sections[0].to_s
    expect(expected_section1).to match_ignoring_whitespace(actual)
  end

  it 'verifies html for second section' do
    actual = outline.sections[1].to_s
    expect(expected_section2).to match_ignoring_whitespace(actual)
  end

  it 'verifies generated html' do
    actual = outline.to_s

    expected = <<~END_EXPECTED
      <div class='outer_posts'>
        #{expected_section1}
        #{expected_section2}
      </div>
    END_EXPECTED

    expect(expected).to match_ignoring_whitespace(actual)
  end
end
