# frozen_string_literal: true

source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '~> 4.2.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'
gem 'sprockets'
gem 'webrick'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_outline', path: "../"
  gem "jekyll_plugin_logger"
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

# Debugging:
gem 'debase', require: false
gem "rake", "~> 13.0", require: false
gem 'rspec', require: false
gem 'rubocop', '= 1.18.0', require: false
gem 'ruby-debug-ide', require: false
