source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'
gem 'ptools'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll_draft', '>= 2.0.2'
  gem 'jekyll-environment-variables'
  gem 'jekyll_img', '>= 0.2.4'
  gem 'jekyll_outline', path: '../'
  gem 'jekyll_plugin_logger'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
